### PR TITLE
chore: remove issue and pull request template so default takes effect

### PR DESCRIPTION
**Pull request by kasparm**
### Purpose
Remove issue and pull request template such that default template in .github repo takes effect

This pull request will server as an example for all the other repositories.

### Time estimate
5 min

### CODE REVIEW

**Review by danielolsen — APPROVED** [review]
Let's see.

**Comment by kasparm** [comment]
It looks like I need to fix some formatting...

**Review by BainanXia — APPROVED** [review]

**Comment by BainanXia** [comment]
> It looks like I need to fix some formatting...

It seems the linter fails due to black upgrades, which we've seen before in other repo and the test fails due to conflict of dependencies.

**Comment by kasparm** [comment]
> > It looks like I need to fix some formatting...
> 
> It seems the linter fails due to black upgrades, which we've seen before in other repo and the test fails due to conflict of dependencies.

I was assuming that... so since I am going to go thorough most of the repo's I will fix all the formatting and dependency issues along the way.

**Comment by rouille** [comment]
We can discard Python 3.7 as we did in the other repos. See https://github.com/Breakthrough-Energy/PowerSimData/pull/582

**Review by rouille — APPROVED** [review]
Looks good

**Pull request merged**
